Repository ACM-VIT/SparkAR-Creators, pull requests merged in 2020-10, with the labels that each got.

#10 added 3D object for issue#7
  Resources/Rigged-Animation Resources/object/character_bellydance.fbx
Labels: hacktoberfest-accepted

#17 rosy02 - added dancing human 3D animation effect as specified in issue #7
  Projects/3D Animations/Rigged-Animation-Project/Dancing Human/human.arproj
  Projects/3D Animations/Rigged-Animation-Project/Dancing Human/human.arprojbk
  Projects/3D Animations/Rigged-Animation-Project/Dancing Human/objects/Character/Character.fbx
  Projects/3D Animations/Rigged-Animation-Project/Dancing Human/objects/character_bellydance/character_bellydance.fbx
  Projects/3D Animations/Rigged-Animation-Project/Dancing Human/project.md
  Projects/3D Animations/Rigged-Animation-Project/Dancing Human/sounds/5bgrr-e2od0.m4a
  Projects/3D Animations/Rigged-Animation-Project/Dancing Human/textures/—Pngtree—sunset at beach with purple_1170442 (2).png
  Projects/3D Animations/Rigged-Animation-Project/human/project.md
Labels: ready-to-merge

#15 Added an effect which usses particle system.
  Projects/Butterflies/Butterflies.arproj
  Projects/Butterflies/sounds/relaxing_piano_music 1.m4a
  Projects/Butterflies/textures/1(1).png
  Projects/Butterflies/textures/1(2).png
  Projects/Butterflies/textures/1.1.png
  Projects/Butterflies/textures/1.png
  Projects/Butterflies/textures/2(2).png
  Projects/Butterflies/textures/2(3).png
  Projects/Butterflies/textures/2(4).png
  Projects/Butterflies/textures/2.png
  Projects/Butterflies/textures/3(1).png
  Projects/Butterflies/textures/3(2).png
  Projects/Butterflies/textures/3(3).png
  Projects/Butterflies/textures/3(4).png
  Projects/Butterflies/textures/4(1).png
  Projects/Butterflies/textures/SkinSmoothingTexture.png
  Projects/Particle-System/Butterflies/Butterflies.arproj
  Projects/Particle-System/Butterflies/sounds/relaxing_piano_music (1).m4a
  Projects/Particle-System/Butterflies/textures/1(1).png
  Projects/Particle-System/Butterflies/textures/1(2).png
  Projects/Particle-System/Butterflies/textures/1.1.png
  Projects/Particle-System/Butterflies/textures/1.png
  Projects/Particle-System/Butterflies/textures/2(2).png
  Projects/Particle-System/Butterflies/textures/2(3).png
  Projects/Particle-System/Butterflies/textures/2(4).png
  Projects/Particle-System/Butterflies/textures/2.png
  Projects/Particle-System/Butterflies/textures/3(1).png
  Projects/Particle-System/Butterflies/textures/3(2).png
  Projects/Particle-System/Butterflies/textures/3(3).png
  Projects/Particle-System/Butterflies/textures/3(4).png
  Projects/Particle-System/Butterflies/textures/4(1).png
Labels: bug, needs-work

#21 Masks added in resources
  Resources/masks/DOGGG.jpg
  Resources/masks/GHOST2.png
  Resources/masks/GHOST3.png
  Resources/masks/GHOST5.png
  Resources/masks/GHOSTTT.png
  Resources/masks/Ghost1.png
  Resources/masks/TATTO1.png
  Resources/masks/redeyes22.png
Labels: hacktoberfest, ready-to-merge

#29 added background segmentation
  Contributing.md
  Projects/Background segmentation/bg-seg-planets/bg-seg.arproj
  Projects/Background segmentation/bg-seg-planets/blocks/Glasses/Glasses.arblock
  Projects/Background segmentation/bg-seg-planets/blocks/Glasses/objects/Glasses/Glasses.fbx
  Projects/Background segmentation/bg-seg-planets/objects/VR headset/L2A VR.obj
  Projects/Background segmentation/bg-seg-planets/objects/headOccluder/headOccluder.fbx
  Projects/Background segmentation/bg-seg-planets/textures/planets@2x.png
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-merged, ready-to-merge

#30 added Scripting effect to #13
  Projects/Scripting/aeroplane/aeroplane.arproj
  Projects/Scripting/aeroplane/objects/out/out.glb
  Projects/Scripting/aeroplane/scripts/script.js
  Projects/Scripting/aeroplane/scripts/tsconfig.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-merged, ready-to-merge

#32 added my details to contributing.md
  Contributing.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-merged
